"""phase8_vendor_templates

Revision ID: 30526fc30d9b
Revises: 9646dbf2266a
Create Date: 2026-07-25 12:23:50.514651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '30526fc30d9b'
down_revision: Union[str, None] = '9646dbf2266a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('header_positions', sa.JSON(), nullable=False),
    sa.Column('invoice_number_location', sa.JSON(), nullable=False),
    sa.Column('date_location', sa.JSON(), nullable=False),
    sa.Column('table_structure', sa.JSON(), nullable=False),
    sa.Column('logo_location', sa.JSON(), nullable=False),
    sa.Column('footer_pattern', sa.JSON(), nullable=False),
    sa.Column('ocr_corrections', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_templates')
    # ### end Alembic commands ###
